import React,{useEffect,useState} from 'react';
import {Alert,Linking,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {CameraView,useCameraPermissions} from 'expo-camera';
import * as Notifications from 'expo-notifications';
import {StatusBar} from 'expo-status-bar';
import {claimFromUrl,getActiveTicket,saveOrder,sendFeedback,Ticket} from './src/api';

Notifications.setNotificationHandler({handleNotification:async()=>({shouldShowBanner:true,shouldShowList:true,shouldPlaySound:true,shouldSetBadge:false})});
export default function App(){const [ticket,setTicket]=useState<Ticket|null>(null);const [scan,setScan]=useState(false);const [perm,requestPerm]=useCameraPermissions();const [order,setOrder]=useState('');const [saved,setSaved]=useState('');
 useEffect(()=>{getActiveTicket().then(setTicket);Linking.getInitialURL().then(u=>u&&claimFromUrl(u).then(setTicket));const s=Linking.addEventListener('url',e=>claimFromUrl(e.url).then(setTicket));Notifications.requestPermissionsAsync();return()=>s.remove()},[]);
 async function openScan(){if(!perm?.granted){const r=await requestPerm();if(!r.granted){Alert.alert('Fotocamera','Permesso necessario per leggere il QR');return}}setScan(true)}
 if(scan)return <SafeAreaView style={styles.scan}><CameraView style={{flex:1}} barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={async({data})=>{setScan(false);setTicket(await claimFromUrl(data))}}/><TouchableOpacity style={styles.close} onPress={()=>setScan(false)}><Text style={styles.closeText}>Chiudi</Text></TouchableOpacity></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><StatusBar style="dark"/><ScrollView contentContainerStyle={styles.wrap}><Text style={styles.logo}>ELIMINACODE</Text><Text style={styles.subtitle}>Il tuo turno, ovunque.</Text>
 {!ticket?<View style={styles.card}><Text style={styles.title}>Prendi il tuo numero</Text><Text style={styles.body}>Al totem scegli il reparto, poi inquadra il QR oppure avvicina il telefono al simbolo NFC.</Text><TouchableOpacity style={styles.primary} onPress={openScan}><Text style={styles.primaryText}>▦ Scansiona QR</Text></TouchableOpacity><Text style={styles.hint}>Per NFC non devi aprire nulla: avvicina il telefono al tag del totem. Se l'app e installata, il link puo aprirla direttamente.</Text></View>:
 <><View style={styles.ticket}><Text style={styles.dept}>{ticket.departmentName}</Text><Text style={styles.num}>{ticket.displayNumber}</Text><Text style={styles.serving}>Stanno servendo {ticket.currentNumber}</Text><Text style={styles.ahead}>{ticket.peopleAhead} persone prima di te • circa {ticket.estimatedMinutes} min</Text></View>
 <View style={styles.card}><Text style={styles.title}>Prepara il tuo ordine</Text><TextInput value={order} onChangeText={setOrder} multiline placeholder="Es. 200 g prosciutto cotto, affettato sottile..." style={styles.input}/><TouchableOpacity style={styles.primary} onPress={async()=>{await saveOrder(ticket.ticketId,order);setSaved('Ordine inviato al reparto')}}><Text style={styles.primaryText}>Invia ordine</Text></TouchableOpacity>{saved&&<Text style={styles.success}>{saved}</Text>}</View>
 <View style={styles.card}><Text style={styles.title}>Come ti sei trovato?</Text><Text style={styles.hint}>Questa sezione verra normalmente mostrata dopo il servizio tramite notifica.</Text><View style={styles.feedback}>{[['😕','poor'],['😐','average'],['🙂','good']].map(([e,r])=><TouchableOpacity key={r} style={styles.fb} onPress={async()=>{await sendFeedback(ticket.ticketId,r as any);Alert.alert('Grazie','Feedback registrato')}}><Text style={{fontSize:30}}>{e}</Text><Text>{r==='poor'?'Scarso':r==='average'?'Medio':'Buono'}</Text></TouchableOpacity>)}</View></View></>}
 </ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f3f7f4'},wrap:{padding:22,gap:16},logo:{fontSize:28,fontWeight:'900',color:'#174b35',marginTop:8},subtitle:{fontSize:16,color:'#6b7c75',marginBottom:8},card:{backgroundColor:'#fff',borderRadius:24,padding:20,gap:14},title:{fontSize:22,fontWeight:'800',color:'#17352a'},body:{fontSize:16,lineHeight:23,color:'#43544e'},primary:{backgroundColor:'#174b35',padding:16,borderRadius:16,alignItems:'center'},primaryText:{color:'#fff',fontSize:17,fontWeight:'800'},hint:{fontSize:13,lineHeight:19,color:'#75857f'},ticket:{backgroundColor:'#174b35',borderRadius:28,padding:26,alignItems:'center'},dept:{color:'#dfeee7',fontSize:20,fontWeight:'700'},num:{color:'#fff',fontSize:76,fontWeight:'900',marginVertical:6},serving:{color:'#fff',fontSize:17},ahead:{color:'#dfeee7',marginTop:10},input:{minHeight:110,borderWidth:1,borderColor:'#d8e2dd',borderRadius:16,padding:14,textAlignVertical:'top'},success:{color:'#26734d',fontWeight:'700'},feedback:{flexDirection:'row',gap:9},fb:{flex:1,backgroundColor:'#f3f7f4',padding:12,borderRadius:16,alignItems:'center',gap:5},scan:{flex:1,backgroundColor:'#000'},close:{position:'absolute',bottom:40,alignSelf:'center',backgroundColor:'#fff',paddingHorizontal:28,paddingVertical:14,borderRadius:20},closeText:{fontWeight:'800'}});
