import React,{useEffect,useRef,useState} from 'react';
import {Alert,AppState,Linking,Platform,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {CameraView,useCameraPermissions} from 'expo-camera';
import * as Notifications from 'expo-notifications';
import * as Speech from 'expo-speech';
import Constants from 'expo-constants';
import {StatusBar} from 'expo-status-bar';
import {claimFromUrl,getActiveTickets,registerPushToken,saveOrder,sendFeedback,Ticket} from './src/api';

Notifications.setNotificationHandler({handleNotification:async()=>({shouldShowBanner:true,shouldShowList:true,shouldPlaySound:true,shouldSetBadge:false})});

type AlertStage='two'|'next'|'turn';
const alertKey=(t:Ticket):AlertStage|null=>t.status==='called'||t.status==='serving'?'turn':t.peopleAhead===1?'next':t.peopleAhead===2?'two':null;
const alertText=(t:Ticket,s:AlertStage)=>s==='two'?`Per ${t.departmentName} mancano due numeri al tuo turno. Il tuo numero è ${t.displayNumber}.`:s==='next'?`Sei il prossimo per ${t.departmentName}. Il tuo numero è ${t.displayNumber}.`:`È il tuo turno. Numero ${t.displayNumber}, recati al banco ${t.departmentName}.`;

export default function App(){
 const [tickets,setTickets]=useState<Ticket[]>([]);const [scan,setScan]=useState(false);const [perm,requestPerm]=useCameraPermissions();const [orderFor,setOrderFor]=useState<string|null>(null);const [order,setOrder]=useState('');const alerted=useRef<Record<string,string>>({});
 async function refresh(){const t=await getActiveTickets();setTickets(t);for(const x of t){const stage=alertKey(x);if(!stage||alerted.current[x.ticketId]===stage)continue;alerted.current[x.ticketId]=stage;const body=alertText(x,stage);await Notifications.scheduleNotificationAsync({content:{title:stage==='turn'?'È il tuo turno':'Eliminacode',body,sound:'default',data:{ticketId:x.ticketId,stage}},trigger:null});if(AppState.currentState==='active')Speech.speak(body,{language:'it-IT',rate:.9});}}
 useEffect(()=>{(async()=>{await Notifications.requestPermissionsAsync();try{const projectId=process.env.EXPO_PUBLIC_EAS_PROJECT_ID||Constants.expoConfig?.extra?.eas?.projectId;if(projectId){const tok=await Notifications.getExpoPushTokenAsync({projectId});await registerPushToken(tok.data,Platform.OS)}}catch{}await refresh()})();
   Linking.getInitialURL().then(async u=>{if(u){try{await claimFromUrl(u);await refresh()}catch(e:any){Alert.alert('QR',e.message)}}});
   const s=Linking.addEventListener('url',async e=>{try{await claimFromUrl(e.url);await refresh()}catch(x:any){Alert.alert('QR',x.message)}}); const timer=setInterval(refresh,10000); return()=>{s.remove();clearInterval(timer)}} ,[]);
 async function openScan(){if(!perm?.granted){const r=await requestPerm();if(!r.granted){Alert.alert('Fotocamera','Permesso necessario per leggere il QR');return}}setScan(true)}
 if(scan)return <SafeAreaView style={styles.scan}><CameraView style={{flex:1}} barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={async({data})=>{setScan(false);try{await claimFromUrl(data);await refresh()}catch(e:any){Alert.alert('QR non valido',e.message)}}}/><TouchableOpacity style={styles.close} onPress={()=>setScan(false)}><Text style={styles.closeText}>Chiudi</Text></TouchableOpacity></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><StatusBar style="dark"/><ScrollView contentContainerStyle={styles.wrap}><Text style={styles.logo}>ELIMINACODE</Text><Text style={styles.subtitle}>I tuoi turni, anche in reparti diversi.</Text>
 <View style={styles.card}><Text style={styles.title}>Aggiungi un turno</Text><Text style={styles.body}>Scansiona il QR del totem oppure il QR stampato sul biglietto. Se è lo stesso ticket mantieni esattamente la stessa priorità.</Text><TouchableOpacity style={styles.primary} onPress={openScan}><Text style={styles.primaryText}>▦ Scansiona QR</Text></TouchableOpacity></View>
 <Text style={styles.section}>I tuoi turni</Text>{tickets.length===0?<View style={styles.empty}><Text>Nessun turno attivo.</Text></View>:tickets.map(t=><View key={t.ticketId} style={[styles.ticket,t.pendingSync&&styles.pending]}><View style={{flex:1}}><Text style={styles.dept}>{t.departmentName}</Text><Text style={styles.num}>{t.displayNumber}</Text><Text style={styles.serving}>{t.pendingSync?'In attesa che il punto vendita torni online':`Stanno servendo ${t.currentNumber}`}</Text><Text style={styles.ahead}>{t.pendingSync?'La priorità resta legata al numero stampato.':t.peopleAhead===0?'È il tuo turno':`${t.peopleAhead} prima di te • circa ${t.estimatedMinutes} min`}</Text></View><TouchableOpacity style={styles.orderBtn} onPress={()=>{setOrderFor(t.ticketId);setOrder('')}}><Text style={styles.orderBtnTxt}>Preordine</Text></TouchableOpacity></View>)}
 {orderFor&&<View style={styles.card}><Text style={styles.title}>Preordine</Text><TextInput value={order} onChangeText={setOrder} multiline placeholder="Es. 200 g prosciutto cotto..." style={styles.input}/><TouchableOpacity style={styles.primary} onPress={async()=>{try{await saveOrder(orderFor,order);setOrderFor(null);Alert.alert('Ordine','Inviato al reparto')}catch(e:any){Alert.alert('Ordine',e.message)}}}><Text style={styles.primaryText}>Invia ordine</Text></TouchableOpacity><TouchableOpacity onPress={()=>setOrderFor(null)}><Text style={styles.cancel}>Annulla</Text></TouchableOpacity></View>}
 <View style={styles.card}><Text style={styles.title}>Avvisi automatici</Text><Text style={styles.hint}>Riceverai un avviso a 2 numeri, a 1 numero e quando viene chiamato il tuo turno. Con l'app attiva l'avviso viene anche pronunciato. Le push da app chiusa vengono inviate dal backend quando è configurato il token push.</Text></View>
 </ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f3f7f4'},wrap:{padding:20,gap:14},logo:{fontSize:28,fontWeight:'900',color:'#174b35',marginTop:8},subtitle:{fontSize:16,color:'#6b7c75',marginBottom:4},section:{fontSize:20,fontWeight:'900',color:'#17352a',marginTop:4},card:{backgroundColor:'#fff',borderRadius:22,padding:18,gap:12},title:{fontSize:21,fontWeight:'800',color:'#17352a'},body:{fontSize:15,lineHeight:22,color:'#43544e'},primary:{backgroundColor:'#174b35',padding:15,borderRadius:15,alignItems:'center'},primaryText:{color:'#fff',fontSize:16,fontWeight:'800'},hint:{fontSize:13,lineHeight:19,color:'#75857f'},ticket:{backgroundColor:'#174b35',borderRadius:24,padding:20,flexDirection:'row',gap:10,alignItems:'center'},pending:{backgroundColor:'#6e6250'},dept:{color:'#dfeee7',fontSize:18,fontWeight:'700'},num:{color:'#fff',fontSize:48,fontWeight:'900',marginVertical:2},serving:{color:'#fff',fontSize:14},ahead:{color:'#dfeee7',marginTop:6},orderBtn:{backgroundColor:'#fff',paddingHorizontal:12,paddingVertical:10,borderRadius:12},orderBtnTxt:{color:'#174b35',fontWeight:'800'},input:{minHeight:105,borderWidth:1,borderColor:'#d8e2dd',borderRadius:15,padding:13,textAlignVertical:'top'},cancel:{textAlign:'center',color:'#687a73',fontWeight:'700'},empty:{backgroundColor:'#fff',borderRadius:20,padding:20},scan:{flex:1,backgroundColor:'#000'},close:{position:'absolute',bottom:40,alignSelf:'center',backgroundColor:'#fff',paddingHorizontal:28,paddingVertical:14,borderRadius:20},closeText:{fontWeight:'800'}});
