import React,{useEffect,useState} from 'react';
import {SafeAreaView,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {action,queue,QueueItem} from './src/api';
export default function App(){const [items,setItems]=useState<QueueItem[]>([]);const [selected,setSelected]=useState<QueueItem|null>(null);const [error,setError]=useState('');
 useEffect(()=>{let alive=true;const load=async()=>{try{const q=await queue();if(alive){setItems(q);setError('');setSelected(s=>s?q.find(x=>x.ticketId===s.ticketId)||null:s)}}catch(e:any){if(alive)setError(e.message)}};load();const t=setInterval(load,2000);return()=>{alive=false;clearInterval(t)}},[]);
 const current=items.find(x=>x.status==='CALLED'||x.status==='SERVING')||null;async function act(i:QueueItem,a:any){try{const n=await action(i.ticketId,a);setItems(n);setSelected(n.find(x=>x.ticketId===i.ticketId)||null);setError('')}catch(e:any){setError(e.message)}}
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.header}><View><Text style={s.logo}>ELIMINACODE</Text><Text style={s.dept}>Tablet reparto • connesso a Supabase</Text></View><View style={s.current}><Text style={s.currentLabel}>IN SERVIZIO</Text><Text style={s.currentNum}>{current?.number||'—'}</Text></View></View>{error?<Text style={s.err}>{error}</Text>:null}<View style={s.body}><View style={s.left}><Text style={s.section}>Coda</Text><ScrollView>{items.map(i=><TouchableOpacity key={i.ticketId} onPress={()=>setSelected(i)} style={[s.row,selected?.ticketId===i.ticketId&&s.rowSel]}><Text style={s.rowNum}>{i.number}</Text><Text style={s.rowInfo}>{i.hasOrder?'🛒 Preordine':'Nessun preordine'}</Text><Text style={s.state}>{i.status}</Text></TouchableOpacity>)}</ScrollView></View><View style={s.right}>{selected?<><Text style={s.ticket}>{selected.number}</Text><Text style={s.orderTitle}>Ordine / note</Text><View style={s.orderBox}><Text style={s.order}>{selected.order||'Nessun ordine inserito.'}</Text></View><View style={s.actions}><TouchableOpacity style={s.primary} onPress={()=>act(selected,'call')}><Text style={s.white}>CHIAMA</Text></TouchableOpacity><TouchableOpacity style={s.ok} onPress={()=>act(selected,'serve')}><Text style={s.white}>SERVITO</Text></TouchableOpacity><TouchableOpacity style={s.secondary} onPress={()=>act(selected,'recall')}><Text style={s.dark}>RICHIAMA</Text></TouchableOpacity><TouchableOpacity style={s.secondary} onPress={()=>act(selected,'skip')}><Text style={s.dark}>SALTA</Text></TouchableOpacity></View></>:<View style={s.empty}><Text style={s.emptyText}>Seleziona un numero dalla coda</Text></View>}</View></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#eef4f0'},header:{height:110,paddingHorizontal:28,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#fff'},logo:{fontWeight:'900',fontSize:28,color:'#174b35'},dept:{fontSize:16,color:'#6f7e78'},current:{alignItems:'center'},currentLabel:{fontSize:12,color:'#6f7e78',fontWeight:'800'},currentNum:{fontSize:44,fontWeight:'900',color:'#174b35'},err:{padding:10,backgroundColor:'#fee2e2',color:'#991b1b'},body:{flex:1,flexDirection:'row',gap:18,padding:18},left:{flex:1.2,backgroundColor:'#fff',borderRadius:22,padding:18},right:{flex:1,backgroundColor:'#fff',borderRadius:22,padding:22},section:{fontSize:22,fontWeight:'900',marginBottom:12,color:'#17352a'},row:{height:72,borderBottomWidth:1,borderBottomColor:'#e7eeea',flexDirection:'row',alignItems:'center',paddingHorizontal:10},rowSel:{backgroundColor:'#edf7f1',borderRadius:14},rowNum:{fontSize:28,fontWeight:'900',width:110,color:'#17352a'},rowInfo:{flex:1,fontSize:16},state:{fontSize:12,fontWeight:'800',color:'#63756e'},ticket:{fontSize:66,fontWeight:'900',color:'#174b35'},orderTitle:{fontSize:17,fontWeight:'800',marginBottom:10},orderBox:{flex:1,minHeight:100,backgroundColor:'#f5f8f6',padding:16,borderRadius:16},order:{fontSize:18,lineHeight:27},actions:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:14},primary:{backgroundColor:'#174b35',padding:16,borderRadius:14,minWidth:130,alignItems:'center'},ok:{backgroundColor:'#287a50',padding:16,borderRadius:14,minWidth:130,alignItems:'center'},secondary:{backgroundColor:'#e8efeb',padding:16,borderRadius:14,minWidth:130,alignItems:'center'},white:{color:'#fff',fontWeight:'900'},dark:{color:'#17352a',fontWeight:'900'},empty:{flex:1,alignItems:'center',justifyContent:'center'},emptyText:{fontSize:20,color:'#718078'}})
