import React,{useEffect,useRef,useState}from'react';import{createClient}from'@supabase/supabase-js';
const url=import.meta.env.VITE_SUPABASE_URL as string;const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;const departmentId=import.meta.env.VITE_DISPLAY_DEPARTMENT_ID as string;
const supabase=url&&key?createClient(url,key):null;
type Current={number:string;department:string;counter?:string};
export default function App(){const[current,setCurrent]=useState<Current>({number:'—',department:'In attesa'});const[last,setLast]=useState('');const[voice,setVoice]=useState(true);const[status,setStatus]=useState('Connessione...');const timer=useRef<any>(null);
 function announce(c:Current){if(!voice||!('speechSynthesis'in window)||!c.number||c.number==='—')return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`Numero ${c.number.split('').join(' ')}, recarsi al banco ${c.department}`);u.lang='it-IT';u.rate=.88;u.pitch=1;window.speechSynthesis.speak(u)}
 async function load(){if(!supabase){setStatus('Modalità demo');return}let q=supabase.from('tickets').select('public_number,status,departments(name)').in('status',['called','serving']).order('called_at',{ascending:false}).limit(1);if(departmentId)q=q.eq('department_id',departmentId);const{data,error}=await q;if(error){setStatus('Errore collegamento');return}const row:any=data?.[0];if(row){const c={number:row.public_number,department:row.departments?.name||'Reparto'};setCurrent(c);setStatus('Online');if(c.number!==last){setLast(c.number);announce(c)}}else{setCurrent({number:'—',department:'In attesa'});setStatus('Online')}}
 useEffect(()=>{load();if(supabase){const ch=supabase.channel('display-calls').on('postgres_changes',{event:'*',schema:'public',table:'tickets'},()=>load()).subscribe(s=>setStatus(s==='SUBSCRIBED'?'Online':s));return()=>{supabase.removeChannel(ch)}}timer.current=setInterval(()=>{const nums=['S041','S042','S043'];const n=nums[Math.floor(Date.now()/8000)%nums.length];const c={number:n,department:'Salumeria'};setCurrent(c);if(n!==last){setLast(n);announce(c)}},1000);return()=>clearInterval(timer.current)},[voice,last]);
 return <main><button className="gear" onClick={()=>window.displayHost.toggleKiosk()}>⚙</button><div className="top"><span className="brand">ELIMINACODE</span><span className={'status '+(status==='Online'?'ok':'')}>{status}</span></div><section><div className="label">ORA SERVIAMO</div><div className="number">{current.number}</div><div className="department">{current.department}</div></section><footer><button onClick={()=>{setVoice(v=>!v);if(voice)window.speechSynthesis.cancel()}}>{voice?'🔊 Voce attiva':'🔇 Voce disattiva'}</button><span>Il numero viene aggiornato automaticamente</span></footer></main>}
